# Workflow graph (entry module) — generated by graphical-agents from the Graph IR (text_stats_workflow).

from langgraph.graph import END, START, StateGraph

from nodes import measure_text, normalize_text, report_stats
from state import WorkflowState

builder = StateGraph(WorkflowState)
builder.add_node("normalize_text", normalize_text)
builder.add_node("measure_text", measure_text)
builder.add_node("report_stats", report_stats)

builder.add_edge(START, "normalize_text")
builder.add_edge("normalize_text", "measure_text")
builder.add_edge("measure_text", "report_stats")
builder.add_edge("report_stats", END)

graph = builder.compile()
