# Node functions (implement the TODO stubs) — generated by graphical-agents from the Graph IR (text_stats_workflow).

from schemas import TextStats
from state import WorkflowState


def _normalize_text_impl(node_input: str) -> str:
    return " ".join(node_input.split()).lower()


def normalize_text(state: WorkflowState) -> dict:
    """Collapse whitespace and lowercase the incoming text."""
    return {"normalize_text_output": _normalize_text_impl(state["workflow_input"])}


def _measure_text_impl(node_input: str) -> TextStats:
    words = len(node_input.split())
    chars = len(node_input)
    return TextStats(words=words, chars=chars)


def measure_text(state: WorkflowState) -> dict:
    """Count words and characters in the normalized text."""
    return {"measure_text_output": _measure_text_impl(state["normalize_text_output"])}


def _report_stats_impl(node_input: TextStats) -> str:
    if node_input.words == 0:
        return "empty passage"

    density = node_input.chars / node_input.words
    return f"{node_input.words} words, {density:.1f} chars/word"


def report_stats(state: WorkflowState) -> dict:
    """Describe the measured text. The guard clause exercises an early return inside a body."""
    return {"report_stats_output": _report_stats_impl(state["measure_text_output"])}
