# Graph state — one key per node output (ADR-0046) — generated by graphical-agents from the Graph IR (text_stats_workflow).

from typing_extensions import TypedDict

from schemas import TextStats


class WorkflowState(TypedDict, total=False):
    workflow_input: str
    normalize_text_output: str
    measure_text_output: TextStats
    report_stats_output: str
