# Function bodies (implement the TODO stubs) — generated by graphical-agents from the Graph IR (text_stats_workflow).

from google.adk import Event

from schemas import TextStats


def _normalize_text_impl(node_input: str) -> str:
    return " ".join(node_input.split()).lower()


def normalize_text(node_input: str) -> Event:
    """Collapse whitespace and lowercase the incoming text."""
    return Event(output=_normalize_text_impl(node_input))


def _measure_text_impl(node_input: str) -> TextStats:
    words = len(node_input.split())
    chars = len(node_input)
    return TextStats(words=words, chars=chars)


def measure_text(node_input: str) -> Event:
    """Count words and characters in the normalized text."""
    return Event(output=_measure_text_impl(node_input))


def _report_stats_impl(node_input: TextStats) -> str:
    if node_input.words == 0:
        return "empty passage"

    density = node_input.chars / node_input.words
    return f"{node_input.words} words, {density:.1f} chars/word"


def report_stats(node_input: TextStats) -> Event:
    """Describe the measured text. The guard clause exercises an early return inside a body."""
    return Event(output=_report_stats_impl(node_input))
