# Workflow graph (entry module) — generated by graphical-agents from the Graph IR (text_stats_workflow).

from google.adk import Workflow

from functions import measure_text, normalize_text, report_stats

root_agent = Workflow(
    name="text_stats_workflow",
    edges=[("START", normalize_text, measure_text, report_stats)],
)
