# Workflow graph (entry module) — generated by graphical-agents from the Graph IR (human_input_workflow).

from langgraph.checkpoint.memory import InMemorySaver
from langgraph.graph import END, START, StateGraph

from nodes import ask_user, process_response
from state import WorkflowState

builder = StateGraph(WorkflowState)
builder.add_node("ask_user", ask_user)
builder.add_node("process_response", process_response)

builder.add_edge(START, "ask_user")
builder.add_edge("ask_user", "process_response")
builder.add_edge("process_response", END)

graph = builder.compile(checkpointer=InMemorySaver())
