# Run the workflow once — generated by graphical-agents from the Graph IR (human_input_workflow).

from uuid import uuid4

from langgraph.types import Command

from graph import graph

# TODO: replace with a real input for this workflow.
SAMPLE_INPUT = "Hello — replace with a real input for this workflow."


def main() -> None:
    config = {"configurable": {"thread_id": f"run-{uuid4().hex[:8]}"}}
    result = graph.invoke({"workflow_input": SAMPLE_INPUT}, config)
    while "__interrupt__" in result:
        print(result["__interrupt__"][0].value["message"])
        result = graph.invoke(Command(resume=input("> ")), config)
    print("Final state:", result)


if __name__ == "__main__":
    main()
