# Node functions (implement the TODO stubs) — generated by graphical-agents from the Graph IR (human_input_workflow).

from langgraph.types import interrupt

from state import WorkflowState


def ask_user(state: WorkflowState) -> dict:
    answer = interrupt(
        {
            "message": "Enter a number to summarize:",
        }
    )
    return {"ask_user_output": answer}


def process_response(state: WorkflowState) -> dict:
    """Forward the human's response."""
    node_input = state["ask_user_output"]
    # TODO: implement process_response — body not yet provided in the IR.
    output: str = ...
    return {"process_response_output": output}
