# Graph state — one key per node output (ADR-0046) — generated by graphical-agents from the Graph IR (human_input_workflow).

from typing_extensions import TypedDict


class WorkflowState(TypedDict, total=False):
    workflow_input: str
    ask_user_output: str
    process_response_output: str
