# Function bodies (implement the TODO stubs) — generated by graphical-agents from the Graph IR (parallel_mid_workflow).

from google.adk import Event


def prep(node_input: str) -> Event:
    """Prepare the shared input before fanning out."""
    # TODO: implement prep — body not yet provided in the IR.
    output: str = ...
    return Event(output=output)


def task_a(node_input: str) -> Event:
    """Parallel branch A."""
    # TODO: implement task_a — body not yet provided in the IR.
    output: str = ...
    return Event(output=output)


def task_b(node_input: str) -> Event:
    """Parallel branch B."""
    # TODO: implement task_b — body not yet provided in the IR.
    output: str = ...
    return Event(output=output)


def final_task(node_input: str) -> Event:
    """Final task after the join."""
    # TODO: implement final_task — body not yet provided in the IR.
    output: str = ...
    return Event(output=output)
