# Run the workflow once — generated by graphical-agents from the Graph IR (parallel_mid_workflow).

import asyncio
from uuid import uuid4

from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.genai import types

from workflow import root_agent

APP_NAME = "parallel_mid_workflow"
USER_ID = "user"

# TODO: replace with a real input for this workflow.
SAMPLE_INPUT = "Hello — replace with a real input for this workflow."


async def main() -> None:
    session_service = InMemorySessionService()
    session_id = f"run-{uuid4().hex[:8]}"
    await session_service.create_session(
        app_name=APP_NAME, user_id=USER_ID, session_id=session_id
    )
    runner = Runner(
        agent=root_agent, app_name=APP_NAME, session_service=session_service
    )
    async for event in runner.run_async(
        user_id=USER_ID,
        session_id=session_id,
        new_message=types.Content(role="user", parts=[types.Part(text=SAMPLE_INPUT)]),
    ):
        print(event)
    final_session = await session_service.get_session(
        app_name=APP_NAME, user_id=USER_ID, session_id=session_id
    )
    print("Final session state:", final_session.state if final_session else {})


if __name__ == "__main__":
    asyncio.run(main())
