# Workflow graph (entry module) — generated by graphical-agents from the Graph IR (parallel_mid_workflow).

from google.adk import Workflow
from google.adk.workflow import JoinNode

from functions import final_task, prep, task_a, task_b

my_join = JoinNode(
    name="my_join",
)

root_agent = Workflow(
    name="parallel_mid_workflow",
    edges=[
        ("START", prep),
        (prep, task_a, my_join),
        (prep, task_b, my_join),
        (my_join, final_task),
    ],
)
