# Loop orchestrators (encapsulated dynamic workflow) — generated by graphical-agents from the Graph IR (critic_loop_workflow).

from typing import Any

from google.adk import Context
from google.adk.agents import LlmAgent
from google.adk.workflow import node
from pydantic import BaseModel

from schemas import (
    Files,
    code_loop_CriticInput,
    code_loop_CriticOutput,
    code_loop_GenInput,
    code_loop_ReviserInput,
)


def validate_node_output(schema_cls: type[BaseModel], raw_output: Any) -> BaseModel:
    if isinstance(raw_output, schema_cls):
        return raw_output
    if isinstance(raw_output, dict):
        return schema_cls.model_validate(raw_output)
    if isinstance(raw_output, BaseModel):
        return schema_cls.model_validate(raw_output.model_dump())
    raise ValueError(f"Cannot validate {type(raw_output)} into {schema_cls}")


@node(rerun_on_resume=True)
async def code_loop_orchestrator(ctx: Context):
    generator = LlmAgent(
        model="gemini-2.5-flash",
        name="code_loop_generator",
        instruction="You are an expert developer. Generate code based on the provided specifications.",
        input_schema=code_loop_GenInput,
        output_schema=Files,
        output_key="code_loop_generated",
    )
    critic = LlmAgent(
        model="gemini-2.5-flash",
        name="code_loop_critic",
        instruction="Review the code against the specifications. If it meets all requirements, return status 'APPROVED'. Otherwise, return detailed feedback.",
        input_schema=code_loop_CriticInput,
        output_schema=code_loop_CriticOutput,
        output_key="code_loop_critic_feedback",
    )
    reviser = LlmAgent(
        model="gemini-2.5-pro",
        name="code_loop_reviser",
        instruction="Fix the provided code based on the critic feedback.",
        input_schema=code_loop_ReviserInput,
        output_schema=Files,
        output_key="code_loop_revised",
    )
    specs = ctx.state.get("code_loop_input", "")
    raw = await ctx.run_node(generator, code_loop_GenInput(specifications=specs))
    current = validate_node_output(Files, raw)
    for _ in range(5):
        critic_raw = await ctx.run_node(critic, code_loop_CriticInput(current=current, specifications=specs))
        crit = validate_node_output(code_loop_CriticOutput, critic_raw)
        if crit.status == "APPROVED":
            ctx.state["code_loop_output"] = current.model_dump()
            return
        revised_raw = await ctx.run_node(reviser, code_loop_ReviserInput(current=current, revision_feedback=crit.feedback))
        current = validate_node_output(Files, revised_raw)
    raise RuntimeError("code_loop failed to produce valid output after 5 rounds")
