# Pytest dry-run (no API key needed) — generated by graphical-agents from the Graph IR (critic_loop_workflow).
"""Free local dry-run — constructs the full graph, calls no model API."""

import os

# Must precede the workflow import: agent construction needs *a* key, not a real one.
os.environ.setdefault("GOOGLE_API_KEY", "test-key")

from google.adk import Workflow

from workflow import root_agent


def test_root_agent_constructs() -> None:
    assert isinstance(root_agent, Workflow)
