# Workflow graph (entry module) — generated by graphical-agents from the Graph IR (critic_loop_workflow).

from google.adk import Workflow

from loops import code_loop_orchestrator

root_agent = Workflow(
    name="critic_loop_workflow",
    edges=[("START", code_loop_orchestrator)],
)
