# Workflow graph (entry module) — generated by graphical-agents from the Graph IR (parallel_join_workflow).

from langgraph.graph import END, START, StateGraph

from nodes import final_task_d, my_join_node, task_a, task_b, task_c
from state import WorkflowState

builder = StateGraph(WorkflowState)
builder.add_node("task_a", task_a)
builder.add_node("task_b", task_b)
builder.add_node("task_c", task_c)
builder.add_node("my_join_node", my_join_node, defer=True)
builder.add_node("final_task_d", final_task_d)

builder.add_edge(START, "task_a")
builder.add_edge(START, "task_b")
builder.add_edge(START, "task_c")
builder.add_edge("task_a", "my_join_node")
builder.add_edge("task_b", "my_join_node")
builder.add_edge("task_c", "my_join_node")
builder.add_edge("my_join_node", "final_task_d")
builder.add_edge("final_task_d", END)

graph = builder.compile()
