# Node functions (implement the TODO stubs) — generated by graphical-agents from the Graph IR (parallel_join_workflow).

from state import WorkflowState


def task_a(state: WorkflowState) -> dict:
    """Parallel branch A."""
    node_input = state["workflow_input"]
    # TODO: implement task_a — body not yet provided in the IR.
    output: str = ...
    return {"task_a_output": output}


def task_b(state: WorkflowState) -> dict:
    """Parallel branch B."""
    node_input = state["workflow_input"]
    # TODO: implement task_b — body not yet provided in the IR.
    output: str = ...
    return {"task_b_output": output}


def task_c(state: WorkflowState) -> dict:
    """Parallel branch C."""
    node_input = state["workflow_input"]
    # TODO: implement task_c — body not yet provided in the IR.
    output: str = ...
    return {"task_c_output": output}


def my_join_node(state: WorkflowState) -> dict:
    """Wait for all parallel branches to complete."""
    return {
        "my_join_node_output": {
            "task_a": state["task_a_output"],
            "task_b": state["task_b_output"],
            "task_c": state["task_c_output"],
        }
    }


def final_task_d(state: WorkflowState) -> dict:
    """Final task after the join."""
    node_input = state["my_join_node_output"]
    # TODO: implement final_task_d — body not yet provided in the IR.
    output: str = ...
    return {"final_task_d_output": output}
