# Graph state — one key per node output (ADR-0046) — generated by graphical-agents from the Graph IR (parallel_join_workflow).

from typing_extensions import TypedDict


class WorkflowState(TypedDict, total=False):
    workflow_input: str
    task_a_output: str
    task_b_output: str
    task_c_output: str
    my_join_node_output: dict
    final_task_d_output: str
