# Agents — generated by graphical-agents from the Graph IR (state_vars_workflow).

from google.adk import Agent

from schemas import Analysis, Expanded, Summary

analyze = Agent(
    name="analyze",
    model="gemini-flash-latest",
    instruction="Identify the single most important key point of the topic.",
    output_schema=Analysis,
)

expand = Agent(
    name="expand",
    model="gemini-flash-latest",
    instruction="Expand this key point into a detailed paragraph: <Analysis.key_point from analyze>",
    input_schema=Analysis,
    output_schema=Expanded,
)

summarize = Agent(
    name="summarize",
    model="gemini-flash-latest",
    instruction="Write a one-line summary of the detail below, staying anchored to the original key point.\n\nDetail: <Expanded.detail from expand>\nOriginal key point: {Analysis.key_point}",
    input_schema=Expanded,
    output_schema=Summary,
)
