# Pydantic schemas — generated by graphical-agents from the Graph IR (state_vars_workflow).

from pydantic import BaseModel


class Analysis(BaseModel):
    key_point: str


class Expanded(BaseModel):
    detail: str


class Summary(BaseModel):
    text: str
