# Workflow graph (entry module) — generated by graphical-agents from the Graph IR (state_vars_workflow).

from google.adk import Workflow

from agents import analyze, expand, summarize

root_agent = Workflow(
    name="state_vars_workflow",
    edges=[("START", analyze, expand, summarize)],
)
