# Run the workflow once — generated by graphical-agents from the Graph IR (feasibility_workflow).
#
# E2E stub overlay. Asserts the router's branch continuation actually ran
# (ADR-0054) — a live cell passes on exit code alone, so a graph that silently
# stopped at the branch target would otherwise report green. LangGraph wires
# continuations as plain `add_edge`, so this is the cross-check against the ADK
# cell rather than the open question itself.

from graph import graph
from nodes import TEST_REPORT

# TODO: replace with a real input for this workflow.
SAMPLE_INPUT = (
    "Add a --retry flag to our CLI that retries failed HTTP requests three "
    "times with exponential backoff."
)


def main() -> None:
    result = graph.invoke({"workflow_input": SAMPLE_INPUT})
    print("Final state:", result)

    # ---- branch-continuation assertions (ADR-0054) ----
    print("\n--- continuation check ---")
    print("state keys:", sorted(result))
    print("route taken:", result.get("feasibility_router_output"))

    failures: list[str] = []
    if result.get("feasibility_router_output") != "FEASIBLE":
        failures.append(
            "the run took the terminal branch, so the continuation was never "
            "exercised — this cell proves nothing as-is"
        )
    if "run_tests_output" not in result:
        failures.append("run_tests never ran — the continuation's second hop is missing")
    if "summarize_result_output" not in result:
        failures.append("summarize_result never ran — the continuation's third hop is missing")
    if result.get("summarize_result_output", "").strip() == TEST_REPORT.strip():
        failures.append("summarize_result echoed the raw report instead of consuming it")

    if failures:
        print("\nCONTINUATION CHECK FAILED:")
        for f in failures:
            print(f"  - {f}")
        raise SystemExit(1)

    print("continuation check OK: route map -> generate_code -> run_tests -> summarize_result")


if __name__ == "__main__":
    main()
