# Workflow graph (entry module) — generated by graphical-agents from the Graph IR (critic_loop_workflow).

from langgraph.graph import END, START, StateGraph

from loops import code_loop
from state import WorkflowState

builder = StateGraph(WorkflowState)
builder.add_node("code_loop", code_loop)

builder.add_edge(START, "code_loop")
builder.add_edge("code_loop", END)

graph = builder.compile()
