# Loop node functions (encapsulated generate→critic→revise) — generated by graphical-agents from the Graph IR (critic_loop_workflow).

from langchain.chat_models import init_chat_model

from schemas import Files, code_loop_CriticOutput
from state import WorkflowState

CODE_LOOP_GENERATOR_INSTRUCTION = (
    "You are an expert developer. Generate code based on the provided specifications."
)
CODE_LOOP_CRITIC_INSTRUCTION = "Review the code against the specifications. If it meets all requirements, return status 'APPROVED'. Otherwise, return detailed feedback."
CODE_LOOP_REVISER_INSTRUCTION = "Fix the provided code based on the critic feedback."


def code_loop(state: WorkflowState) -> dict:
    """Generate code, then loop critic+reviser until the critic approves."""
    specifications = state["workflow_input"]
    generator = init_chat_model("google_genai:gemini-2.5-flash")
    critic = init_chat_model("google_genai:gemini-2.5-flash")
    reviser = init_chat_model("google_genai:gemini-2.5-pro")
    current = generator.with_structured_output(Files).invoke(
        f"{CODE_LOOP_GENERATOR_INSTRUCTION}\n\nSpecifications:\n{specifications}",
    )
    for _ in range(5):
        crit = critic.with_structured_output(code_loop_CriticOutput).invoke(
            f"{CODE_LOOP_CRITIC_INSTRUCTION}\n\nCurrent:\n{current.model_dump_json()}\n\nSpecifications:\n{specifications}",
        )
        if crit.status == "APPROVED":
            return {"code_loop_output": current}
        current = reviser.with_structured_output(Files).invoke(
            f"{CODE_LOOP_REVISER_INSTRUCTION}\n\nCritic feedback:\n{crit.feedback}\n\nCurrent:\n{current.model_dump_json()}",
        )
    raise RuntimeError("code_loop failed to produce valid output after 5 rounds")
