# Pydantic schemas — generated by graphical-agents from the Graph IR (critic_loop_workflow).

from pydantic import BaseModel


class FileItem(BaseModel):
    filename: str
    content: str


class Files(BaseModel):
    items: FileItem


class code_loop_CriticOutput(BaseModel):
    status: str
    feedback: str
