# Graph state — one key per node output (ADR-0046) — generated by graphical-agents from the Graph IR (critic_loop_workflow).

from typing_extensions import TypedDict

from schemas import Files


class WorkflowState(TypedDict, total=False):
    workflow_input: str
    code_loop_output: Files
