# Workflow graph (entry module) — generated by graphical-agents from the Graph IR (nested_parent_workflow).

from langgraph.graph import END, START, StateGraph

from nodes import finalize, inner_step_a, inner_step_b, preprocess
from state import NestedWorkflowState, WorkflowState

nested_workflow_builder = StateGraph(NestedWorkflowState)
nested_workflow_builder.add_node("inner_step_a", inner_step_a)
nested_workflow_builder.add_node("inner_step_b", inner_step_b)

nested_workflow_builder.add_edge(START, "inner_step_a")
nested_workflow_builder.add_edge("inner_step_a", "inner_step_b")
nested_workflow_builder.add_edge("inner_step_b", END)

nested_workflow_graph = nested_workflow_builder.compile()


def nested_workflow(state: WorkflowState) -> dict:
    """Nested sub-graph compiled as its own Workflow(...) object."""
    sub_state = nested_workflow_graph.invoke(
        {"workflow_input": state["preprocess_output"]}
    )
    return {"nested_workflow_output": sub_state["inner_step_b_output"]}


builder = StateGraph(WorkflowState)
builder.add_node("preprocess", preprocess)
builder.add_node("nested_workflow", nested_workflow)
builder.add_node("finalize", finalize)

builder.add_edge(START, "preprocess")
builder.add_edge("preprocess", "nested_workflow")
builder.add_edge("nested_workflow", "finalize")
builder.add_edge("finalize", END)

graph = builder.compile()
