# Node functions (implement the TODO stubs) — generated by graphical-agents from the Graph IR (nested_parent_workflow).

from state import NestedWorkflowState, WorkflowState


def preprocess(state: WorkflowState) -> dict:
    """Parent: prepare input for the nested workflow."""
    node_input = state["workflow_input"]
    # TODO: implement preprocess — body not yet provided in the IR.
    output: str = ...
    return {"preprocess_output": output}


def inner_step_a(state: NestedWorkflowState) -> dict:
    """Inner step A."""
    node_input = state["workflow_input"]
    # TODO: implement inner_step_a — body not yet provided in the IR.
    output: str = ...
    return {"inner_step_a_output": output}


def inner_step_b(state: NestedWorkflowState) -> dict:
    """Inner step B."""
    node_input = state["inner_step_a_output"]
    # TODO: implement inner_step_b — body not yet provided in the IR.
    output: str = ...
    return {"inner_step_b_output": output}


def finalize(state: WorkflowState) -> dict:
    """Parent: finalize after the nested workflow returns."""
    node_input = state["nested_workflow_output"]
    # TODO: implement finalize — body not yet provided in the IR.
    output: str = ...
    return {"finalize_output": output}
