# Graph state — one key per node output (ADR-0046) — generated by graphical-agents from the Graph IR (nested_parent_workflow).

from typing_extensions import TypedDict


class NestedWorkflowState(TypedDict, total=False):
    workflow_input: str
    inner_step_a_output: str
    inner_step_b_output: str


class WorkflowState(TypedDict, total=False):
    workflow_input: str
    preprocess_output: str
    nested_workflow_output: str
    finalize_output: str
