# Pytest dry-run (no API key needed) — generated by graphical-agents from the Graph IR (nested_parent_workflow).
"""Free local dry-run — builds and compiles the StateGraph, calls no model API."""

import os

# Must precede the graph import: models are constructed lazily inside node
# functions, so no key is needed — this is belt-and-braces.
os.environ.setdefault("GOOGLE_API_KEY", "test-key")

from graph import graph


def test_graph_builds() -> None:
    assert "preprocess" in graph.get_graph().nodes
