# Function bodies (implement the TODO stubs) — generated by graphical-agents from the Graph IR (human_input_workflow).

from google.adk import Event
from google.adk.events import RequestInput


def ask_user():
    yield RequestInput(
        message="Enter a number to summarize:",
    )


def process_response(node_input: str) -> Event:
    """Forward the human's response."""
    # TODO: implement process_response — body not yet provided in the IR.
    output: str = ...
    return Event(output=output)
