# Workflow graph (entry module) — generated by graphical-agents from the Graph IR (human_input_workflow).

from google.adk import Workflow

from functions import ask_user, process_response

root_agent = Workflow(
    name="human_input_workflow",
    edges=[("START", ask_user, process_response)],
)
