# Workflow graph (entry module) — generated by graphical-agents from the Graph IR (support_router_workflow).

from langgraph.graph import END, START, StateGraph

from agents import (
    handle_bug,
    handle_customer_support,
    handle_logistics,
    process_message,
)
from nodes import router
from state import WorkflowState

builder = StateGraph(WorkflowState)
builder.add_node("process_message", process_message)
builder.add_node("router", router)
builder.add_node("handle_bug", handle_bug)
builder.add_node("handle_customer_support", handle_customer_support)
builder.add_node("handle_logistics", handle_logistics)

builder.add_edge(START, "process_message")
builder.add_edge("process_message", "router")
builder.add_conditional_edges(
    "router",
    lambda state: state["router_output"],
    {
        "BUG": "handle_bug",
        "CUSTOMER_SUPPORT": "handle_customer_support",
        "LOGISTICS": "handle_logistics",
    },
)
builder.add_edge("handle_bug", END)
builder.add_edge("handle_customer_support", END)
builder.add_edge("handle_logistics", END)

graph = builder.compile()
