# Node functions (implement the TODO stubs) — generated by graphical-agents from the Graph IR (support_router_workflow).

from state import WorkflowState


def router(state: WorkflowState) -> dict:
    """Route the support message to the matching handler."""
    node_input = state["process_message_output"]
    # TODO: implement router — return one of: BUG, CUSTOMER_SUPPORT, LOGISTICS.
    route: str = ...
    return {"router_output": route}
