# Graph state — one key per node output (ADR-0046) — generated by graphical-agents from the Graph IR (support_router_workflow).

from typing_extensions import TypedDict


class WorkflowState(TypedDict, total=False):
    workflow_input: str
    process_message_output: str
    router_output: str
    handle_bug_output: str
    handle_customer_support_output: str
    handle_logistics_output: str
