# Workflow graph (entry module) — generated by graphical-agents from the Graph IR (parallel_mid_workflow).

from langgraph.graph import END, START, StateGraph

from nodes import final_task, my_join, prep, task_a, task_b
from state import WorkflowState

builder = StateGraph(WorkflowState)
builder.add_node("prep", prep)
builder.add_node("task_a", task_a)
builder.add_node("task_b", task_b)
builder.add_node("my_join", my_join, defer=True)
builder.add_node("final_task", final_task)

builder.add_edge(START, "prep")
builder.add_edge("prep", "task_a")
builder.add_edge("prep", "task_b")
builder.add_edge("task_a", "my_join")
builder.add_edge("task_b", "my_join")
builder.add_edge("my_join", "final_task")
builder.add_edge("final_task", END)

graph = builder.compile()
