# Node functions (implement the TODO stubs) — generated by graphical-agents from the Graph IR (parallel_mid_workflow).

from state import WorkflowState


def prep(state: WorkflowState) -> dict:
    """Prepare the shared input before fanning out."""
    node_input = state["workflow_input"]
    # TODO: implement prep — body not yet provided in the IR.
    output: str = ...
    return {"prep_output": output}


def task_a(state: WorkflowState) -> dict:
    """Parallel branch A."""
    node_input = state["prep_output"]
    # TODO: implement task_a — body not yet provided in the IR.
    output: str = ...
    return {"task_a_output": output}


def task_b(state: WorkflowState) -> dict:
    """Parallel branch B."""
    node_input = state["prep_output"]
    # TODO: implement task_b — body not yet provided in the IR.
    output: str = ...
    return {"task_b_output": output}


def my_join(state: WorkflowState) -> dict:
    """Wait for both branches to complete."""
    return {
        "my_join_output": {
            "task_a": state["task_a_output"],
            "task_b": state["task_b_output"],
        }
    }


def final_task(state: WorkflowState) -> dict:
    """Final task after the join."""
    node_input = state["my_join_output"]
    # TODO: implement final_task — body not yet provided in the IR.
    output: str = ...
    return {"final_task_output": output}
