# Graph state — one key per node output (ADR-0046) — generated by graphical-agents from the Graph IR (parallel_mid_workflow).

from typing_extensions import TypedDict


class WorkflowState(TypedDict, total=False):
    workflow_input: str
    prep_output: str
    task_a_output: str
    task_b_output: str
    my_join_output: dict
    final_task_output: str
