# Agents — generated by graphical-agents from the Graph IR (feasibility_workflow).

from google.adk import Agent

assess_request = Agent(
    name="assess_request",
    model="gemini-flash-latest",
    instruction="Read the incoming feature request and summarize what it would take to build, in one paragraph.",
    output_schema=str,
)

generate_code = Agent(
    name="generate_code",
    model="gemini-flash-latest",
    instruction="Write the implementation for the assessed feature request. Return only the code.",
    output_schema=str,
)

summarize_result = Agent(
    name="summarize_result",
    model="gemini-flash-latest",
    instruction="Summarize the test report for the requester: what passed, what failed, and what to do next.",
    output_schema=str,
)

explain_blockers = Agent(
    name="explain_blockers",
    model="gemini-flash-latest",
    instruction="Explain why the request cannot be built as stated, and describe what would have to change.",
    output_schema=str,
)
