# Workflow graph (entry module) — generated by graphical-agents from the Graph IR (feasibility_workflow).

from google.adk import Workflow

from agents import assess_request, explain_blockers, generate_code, summarize_result
from functions import feasibility_router, run_tests

root_agent = Workflow(
    name="feasibility_workflow",
    edges=[
        ("START", assess_request, feasibility_router),
        (
            feasibility_router,
            {"FEASIBLE": generate_code, "INFEASIBLE": explain_blockers},
        ),
        (generate_code, run_tests, summarize_result),
    ],
)
