# Workflow graph (entry module) — generated by graphical-agents from the Graph IR (city_time_workflow).

from langgraph.graph import END, START, StateGraph

from agents import city_generator, city_report
from nodes import completed_message, lookup_time
from state import WorkflowState

builder = StateGraph(WorkflowState)
builder.add_node("city_generator", city_generator)
builder.add_node("lookup_time", lookup_time)
builder.add_node("city_report", city_report)
builder.add_node("completed_message", completed_message)

builder.add_edge(START, "city_generator")
builder.add_edge("city_generator", "lookup_time")
builder.add_edge("lookup_time", "city_report")
builder.add_edge("city_report", "completed_message")
builder.add_edge("completed_message", END)

graph = builder.compile()
