# Node functions (implement the TODO stubs) — generated by graphical-agents from the Graph IR (city_time_workflow).

from schemas import CityTime
from state import WorkflowState


def lookup_time(state: WorkflowState) -> dict:
    """Return the current time in the given city."""
    node_input = state["city_generator_output"]
    # TODO: implement lookup_time — body not yet provided in the IR.
    output: CityTime = ...
    return {"lookup_time_output": output}


def completed_message(state: WorkflowState) -> dict:
    """Append a workflow-completed notice to the report."""
    node_input = state["city_report_output"]
    # TODO: implement completed_message — body not yet provided in the IR.
    output: str = ...
    return {"completed_message_output": output}
