# Graph state — one key per node output (ADR-0046) — generated by graphical-agents from the Graph IR (city_time_workflow).

from typing_extensions import TypedDict

from schemas import CityTime


class WorkflowState(TypedDict, total=False):
    workflow_input: str
    city_generator_output: str
    lookup_time_output: CityTime
    city_report_output: str
    completed_message_output: str
