# Workflow graph (entry module) — generated by graphical-agents from the Graph IR (parallel_join_workflow).

from google.adk import Workflow
from google.adk.workflow import JoinNode

from functions import final_task_d, task_a, task_b, task_c

my_join_node = JoinNode(
    name="my_join_node",
)

root_agent = Workflow(
    name="parallel_join_workflow",
    edges=[("START", task_a, my_join_node), ("START", task_b, my_join_node), ("START", task_c, my_join_node), (my_join_node, final_task_d)],
)
