/**
 * Project assembler — GraphIR → a runnable ADK project file set (ARCHITECTURE.md
 * §5). This is the orchestrator of the codegen pipeline: it runs the edges
 * compiler, dispatches per-node template fragments (ADR-0003), dedupes their
 * imports, and assembles the modules + scaffold files.
 *
 * Scope mirrors the edges-compiler slice (ADR-0010): linear graphs of agent and
 * function nodes only. compileEdges rejects out-of-slice graph *shapes* (routers,
 * joins, parallel) loud; this module additionally rejects out-of-slice node
 * *types* (tool, workflow) loud. `black` is the post-process formatter and is not
 * run yet — fragments emit black-shaped text so that step is a near no-op.
 */
import type {
  AgentNode,
  FunctionNode,
  GraphIR,
  JoinNode,
  RouterNode,
  SchemaDef,
} from "@graphical-agents/ir";
import { compileEdges, renderEdgeRows, type EdgeRow } from "./edges.ts";
import {
  indexSchemas,
  renderAgent,
  renderFunction,
  renderJoin,
  renderRouter,
  renderSchema,
  type Fragment,
} from "./fragments.ts";
import { CodegenError, type ImportReq, indent, pyStr, renderImports } from "./python.ts";

/** A generated project: file path (relative to the project root) → file content. */
export type GeneratedProject = Map<string, string>;

const REQUIREMENTS = "google-adk==2.0.0\n";

const ENV_EXAMPLE = `# Google ADK credentials — copy this file to .env and fill in your key.
GOOGLE_API_KEY=
`;

/** Compile an IR into the runnable ADK project file set. */
export function generateProject(ir: GraphIR): GeneratedProject {
  // Reject out-of-slice graph shapes (routers, joins, parallel, no START) loud.
  const rows = compileEdges(ir);
  const schemas = indexSchemas(ir);

  // Reject out-of-slice node types loud — agent + function + router + join this slice.
  for (const node of ir.nodes) {
    if (node.type !== "agent" && node.type !== "function" && node.type !== "router" && node.type !== "join") {
      throw new CodegenError(
        `node "${node.name}" of type "${node.type}" is not handled by the ` +
          "agent+function+router+join slice",
      );
    }
  }

  const agents = ir.nodes.filter((n): n is AgentNode => n.type === "agent");
  const functions = ir.nodes.filter((n): n is FunctionNode => n.type === "function");
  const routers = ir.nodes.filter((n): n is RouterNode => n.type === "router");
  const joins = ir.nodes.filter((n): n is JoinNode => n.type === "join");

  const files: GeneratedProject = new Map();
  files.set("schemas.py", schemasModule(ir, ir.schemas, schemas));
  files.set("functions.py", functionsModule(ir, functions, routers, schemas));
  files.set("agents.py", agentsModule(ir, agents, schemas));
  files.set("workflow.py", workflowModule(ir, rows, agents, functions, routers, joins));
  files.set("requirements.txt", REQUIREMENTS);
  files.set(".env.example", ENV_EXAMPLE);
  files.set("README.md", readme(ir));
  return files;
}

function header(title: string, ir: GraphIR): string {
  return `# ${title} — generated by graphical-agents from the Graph IR (${ir.name}).`;
}

/**
 * Stitch a header, deduped imports, and bodies into one module. `kind` controls
 * black's blank-line policy: two blank lines around top-level `def`/`class`,
 * one around plain assignments.
 */
function joinModule(
  head: string,
  imports: readonly ImportReq[],
  bodies: readonly string[],
  kind: "def" | "stmt",
): string {
  const importBlock = renderImports(imports);
  const gap = kind === "def" ? "\n\n\n" : "\n\n";
  const body = bodies.map((b) => b.replace(/\n+$/, "")).join(gap);
  const prefix = importBlock ? `${head}\n\n${importBlock}` : head;
  if (bodies.length === 0) return `${prefix}\n`;
  return `${prefix}${gap}${body}\n`;
}

function schemasModule(
  ir: GraphIR,
  schemaDefs: readonly SchemaDef[],
  _schemas: ReadonlyMap<string, SchemaDef>,
): string {
  const head = header("Pydantic schemas", ir);
  if (schemaDefs.length === 0) {
    return `${head}\n\n# No schemas declared in the IR.\n`;
  }
  const frags = schemaDefs.map(renderSchema);
  return joinModule(head, frags.flatMap((f) => f.imports), frags.map((f) => f.code), "def");
}

function functionsModule(
  ir: GraphIR,
  functions: readonly FunctionNode[],
  routers: readonly RouterNode[],
  schemas: ReadonlyMap<string, SchemaDef>,
): string {
  const head = header("Function bodies (implement the TODO stubs)", ir);
  if (functions.length === 0 && routers.length === 0) {
    return `${head}\n\n# No function or router nodes in the IR.\n`;
  }
  // Render in IR node order so function and router defs interleave naturally.
  const byId = new Set<string>([...functions, ...routers].map((n) => n.id));
  const frags: Fragment[] = ir.nodes
    .filter((n) => byId.has(n.id))
    .map((n) =>
      n.type === "router"
        ? renderRouter(n as RouterNode, schemas)
        : renderFunction(n as FunctionNode, schemas),
    );
  return joinModule(head, frags.flatMap((f) => f.imports), frags.map((f) => f.code), "def");
}

function agentsModule(
  ir: GraphIR,
  agents: readonly AgentNode[],
  schemas: ReadonlyMap<string, SchemaDef>,
): string {
  const head = header("Agents", ir);
  if (agents.length === 0) return `${head}\n\n# No agent nodes in the IR.\n`;
  const frags: Fragment[] = agents.map((n) => renderAgent(n, schemas));
  return joinModule(head, frags.flatMap((f) => f.imports), frags.map((f) => f.code), "stmt");
}

function workflowModule(
  ir: GraphIR,
  rows: readonly EdgeRow[],
  agents: readonly AgentNode[],
  functions: readonly FunctionNode[],
  routers: readonly RouterNode[],
  joins: readonly JoinNode[],
): string {
  const head = header("Workflow graph (entry module)", ir);
  const imports: ImportReq[] = [{ module: "google.adk", names: ["Workflow"] }];
  if (agents.length > 0) imports.push({ module: "agents", names: agents.map((a) => a.name) });
  // Routers live in functions.py too, and their symbols appear in the edge rows.
  const fnNames = [...functions.map((f) => f.name), ...routers.map((r) => r.name)];
  if (fnNames.length > 0) imports.push({ module: "functions", names: fnNames });

  // JoinNode declarations are rendered inline in workflow.py.
  const joinFrags: Fragment[] = joins.map((j) => renderJoin(j));
  for (const frag of joinFrags) imports.push(...frag.imports);

  const kwargs = `name=${pyStr(ir.name)},\n${renderEdgeRows(rows)},`;
  const workflowBody = `root_agent = Workflow(\n${indent(kwargs)}\n)\n`;

  // Join declarations come before the Workflow so the symbol is available.
  const bodies = [...joinFrags.map((f) => f.code), workflowBody];
  return joinModule(head, imports, bodies, "stmt");
}

function readme(ir: GraphIR): string {
  const description = ir.description ? `${ir.description}\n\n` : "";
  return `# ${ir.name}

${description}Generated by **graphical-agents** from the Graph IR — a runnable Google ADK
(graph-workflow, v2.0.0) project.

## Layout

| File | Contents |
| --- | --- |
| \`schemas.py\` | Pydantic models for every IR schema. |
| \`functions.py\` | One function per function node. **Implement the \`TODO\` stubs.** |
| \`agents.py\` | One \`Agent\` per agent node. |
| \`workflow.py\` | \`root_agent = Workflow(edges=[...])\` — the graph entry point. |

## Run

1. \`pip install -r requirements.txt\`
2. Copy \`.env.example\` to \`.env\` and fill in your credentials.
3. Implement the \`TODO\` stubs in \`functions.py\`.
4. Run with the ADK runtime (e.g. \`adk run workflow.py\`).
`;
}
