# Agents — generated by graphical-agents from the Graph IR (city_time_workflow).

from google.adk import Agent

from schemas import CityTime

city_generator = Agent(
    name="city_generator",
    model="gemini-flash-latest",
    instruction="Return the name of a random city. Return only the name, nothing else.",
    output_schema=str,
)

city_report = Agent(
    name="city_report",
    model="gemini-flash-latest",
    instruction="Output the following line:\nIt is <CityTime.time_info from lookup_time> in <CityTime.city from lookup_time> right now.",
    input_schema=CityTime,
    output_schema=str,
)
