# Function bodies (implement the TODO stubs) — generated by graphical-agents from the Graph IR (city_time_workflow).

from google.adk import Event

from schemas import CityTime


def lookup_time(node_input: str) -> Event:
    """Return the current time in the given city."""
    # TODO: implement lookup_time — body not yet provided in the IR.
    output: CityTime = ...
    return Event(output=output)


def completed_message(node_input: str) -> Event:
    """Append a workflow-completed notice to the report."""
    # TODO: implement completed_message — body not yet provided in the IR.
    message: str = ...
    return Event(message=message)
