# Workflow graph (entry module) — generated by graphical-agents from the Graph IR (city_time_workflow).

from google.adk import Workflow

from agents import city_generator, city_report
from functions import completed_message, lookup_time

root_agent = Workflow(
    name="city_time_workflow",
    edges=[("START", city_generator, lookup_time, city_report, completed_message)],
)
