# Function bodies (implement the TODO stubs) — generated by graphical-agents from the Graph IR (nested_parent_workflow).

from google.adk import Event


def preprocess(node_input: str) -> Event:
    """Parent: prepare input for the nested workflow."""
    # TODO: implement preprocess — body not yet provided in the IR.
    output: str = ...
    return Event(output=output)


def inner_step_a(node_input: str) -> Event:
    """Inner step A."""
    # TODO: implement inner_step_a — body not yet provided in the IR.
    output: str = ...
    return Event(output=output)


def inner_step_b(node_input: str) -> Event:
    """Inner step B."""
    # TODO: implement inner_step_b — body not yet provided in the IR.
    output: str = ...
    return Event(output=output)


def finalize(node_input: str) -> Event:
    """Parent: finalize after the nested workflow returns."""
    # TODO: implement finalize — body not yet provided in the IR.
    output: str = ...
    return Event(output=output)
