# Workflow graph (entry module) — generated by graphical-agents from the Graph IR (nested_parent_workflow).

from google.adk import Workflow

from functions import finalize, inner_step_a, inner_step_b, preprocess

nested_workflow = Workflow(
    name="nested_workflow",
    edges=[("START", inner_step_a, inner_step_b)],
)

root_agent = Workflow(
    name="nested_parent_workflow",
    edges=[("START", preprocess, nested_workflow, finalize)],
)
