# Agent node functions — generated by graphical-agents from the Graph IR (feasibility_workflow).

from langchain.chat_models import init_chat_model

from state import WorkflowState


def assess_request(state: WorkflowState) -> dict:
    model = init_chat_model("google_genai:gemini-flash-latest")
    prompt = f"Read the incoming feature request and summarize what it would take to build, in one paragraph.\n\nInput:\n{state['workflow_input']}"
    result = model.invoke(prompt)
    return {"assess_request_output": result.text}


def generate_code(state: WorkflowState) -> dict:
    model = init_chat_model("google_genai:gemini-flash-latest")
    prompt = f"Write the implementation for the assessed feature request. Return only the code.\n\nInput:\n{state['assess_request_output']}"
    result = model.invoke(prompt)
    return {"generate_code_output": result.text}


def summarize_result(state: WorkflowState) -> dict:
    model = init_chat_model("google_genai:gemini-flash-latest")
    prompt = f"Summarize the test report for the requester: what passed, what failed, and what to do next.\n\nInput:\n{state['run_tests_output']}"
    result = model.invoke(prompt)
    return {"summarize_result_output": result.text}


def explain_blockers(state: WorkflowState) -> dict:
    model = init_chat_model("google_genai:gemini-flash-latest")
    prompt = f"Explain why the request cannot be built as stated, and describe what would have to change.\n\nInput:\n{state['assess_request_output']}"
    result = model.invoke(prompt)
    return {"explain_blockers_output": result.text}
