# Workflow graph (entry module) — generated by graphical-agents from the Graph IR (feasibility_workflow).

from langgraph.graph import END, START, StateGraph

from agents import assess_request, explain_blockers, generate_code, summarize_result
from nodes import feasibility_router, run_tests
from state import WorkflowState

builder = StateGraph(WorkflowState)
builder.add_node("assess_request", assess_request)
builder.add_node("feasibility_router", feasibility_router)
builder.add_node("generate_code", generate_code)
builder.add_node("run_tests", run_tests)
builder.add_node("summarize_result", summarize_result)
builder.add_node("explain_blockers", explain_blockers)

builder.add_edge(START, "assess_request")
builder.add_edge("assess_request", "feasibility_router")
builder.add_conditional_edges(
    "feasibility_router",
    lambda state: state["feasibility_router_output"],
    {
        "FEASIBLE": "generate_code",
        "INFEASIBLE": "explain_blockers",
    },
)
builder.add_edge("generate_code", "run_tests")
builder.add_edge("run_tests", "summarize_result")
builder.add_edge("summarize_result", END)
builder.add_edge("explain_blockers", END)

graph = builder.compile()
