# Node functions (implement the TODO stubs) — generated by graphical-agents from the Graph IR (feasibility_workflow).

from state import WorkflowState


def feasibility_router(state: WorkflowState) -> dict:
    """Decide whether the assessed request is feasible to build now."""
    node_input = state["assess_request_output"]
    # TODO: implement feasibility_router — return one of: FEASIBLE, INFEASIBLE.
    route: str = ...
    return {"feasibility_router_output": route}


def run_tests(state: WorkflowState) -> dict:
    """Run the project's test suite against the generated code and return the report."""
    node_input = state["generate_code_output"]
    # TODO: implement run_tests — body not yet provided in the IR.
    output: str = ...
    return {"run_tests_output": output}
