# Graph state — one key per node output (ADR-0046) — generated by graphical-agents from the Graph IR (feasibility_workflow).

from typing_extensions import TypedDict


class WorkflowState(TypedDict, total=False):
    workflow_input: str
    assess_request_output: str
    feasibility_router_output: str
    generate_code_output: str
    run_tests_output: str
    summarize_result_output: str
    explain_blockers_output: str
