# Agent node functions — generated by graphical-agents from the Graph IR (nested_schema_workflow).

from langchain.chat_models import init_chat_model

from schemas import Order
from state import WorkflowState


def make_order(state: WorkflowState) -> dict:
    model = init_chat_model("google_genai:gemini-flash-latest")
    prompt = f"Produce a sample Order with a customer and an optional shipping_address.\n\nInput:\n{state['workflow_input']}"
    result = model.with_structured_output(Order).invoke(prompt)
    return {"make_order_output": result}
