# Workflow graph (entry module) — generated by graphical-agents from the Graph IR (nested_schema_workflow).

from langgraph.graph import END, START, StateGraph

from agents import make_order
from nodes import summarize_order
from state import WorkflowState

builder = StateGraph(WorkflowState)
builder.add_node("make_order", make_order)
builder.add_node("summarize_order", summarize_order)

builder.add_edge(START, "make_order")
builder.add_edge("make_order", "summarize_order")
builder.add_edge("summarize_order", END)

graph = builder.compile()
