# Node functions (implement the TODO stubs) — generated by graphical-agents from the Graph IR (nested_schema_workflow).

from state import WorkflowState


def summarize_order(state: WorkflowState) -> dict:
    """Render the order as a one-line human-readable string."""
    node_input = state["make_order_output"]
    # TODO: implement summarize_order — body not yet provided in the IR.
    output: str = ...
    return {"summarize_order_output": output}
