# Pydantic schemas — generated by graphical-agents from the Graph IR (nested_schema_workflow).

from typing import Optional

from pydantic import BaseModel


class Customer(BaseModel):
    name: str
    email: str


class Order(BaseModel):
    order_id: str
    customer: Customer
    shipping_address: Optional[Customer] = None
