# Graph state — one key per node output (ADR-0046) — generated by graphical-agents from the Graph IR (nested_schema_workflow).

from typing_extensions import TypedDict

from schemas import Order


class WorkflowState(TypedDict, total=False):
    workflow_input: str
    make_order_output: Order
    summarize_order_output: str
