# Agent node functions — generated by graphical-agents from the Graph IR (state_vars_workflow).

from langchain.chat_models import init_chat_model

from schemas import Analysis, Expanded, Summary
from state import WorkflowState


def analyze(state: WorkflowState) -> dict:
    model = init_chat_model("google_genai:gemini-flash-latest")
    prompt = f"Identify the single most important key point of the topic.\n\nInput:\n{state['workflow_input']}"
    result = model.with_structured_output(Analysis).invoke(prompt)
    return {"analyze_output": result}


def expand(state: WorkflowState) -> dict:
    model = init_chat_model("google_genai:gemini-flash-latest")
    prompt = f"Expand this key point into a detailed paragraph: {state['analyze_output'].key_point}"
    result = model.with_structured_output(Expanded).invoke(prompt)
    return {"expand_output": result}


def summarize(state: WorkflowState) -> dict:
    model = init_chat_model("google_genai:gemini-flash-latest")
    prompt = f"Write a one-line summary of the detail below, staying anchored to the original key point.\n\nDetail: {state['expand_output'].detail}\nOriginal key point: {state['analyze_output'].key_point}"
    result = model.with_structured_output(Summary).invoke(prompt)
    return {"summarize_output": result}
