# Workflow graph (entry module) — generated by graphical-agents from the Graph IR (state_vars_workflow).

from langgraph.graph import END, START, StateGraph

from agents import analyze, expand, summarize
from state import WorkflowState

builder = StateGraph(WorkflowState)
builder.add_node("analyze", analyze)
builder.add_node("expand", expand)
builder.add_node("summarize", summarize)

builder.add_edge(START, "analyze")
builder.add_edge("analyze", "expand")
builder.add_edge("expand", "summarize")
builder.add_edge("summarize", END)

graph = builder.compile()
