# Graph state — one key per node output (ADR-0046) — generated by graphical-agents from the Graph IR (state_vars_workflow).

from typing_extensions import TypedDict

from schemas import Analysis, Expanded, Summary


class WorkflowState(TypedDict, total=False):
    workflow_input: str
    analyze_output: Analysis
    expand_output: Expanded
    summarize_output: Summary
