# Agents — generated by graphical-agents from the Graph IR (support_router_workflow).

from google.adk import Agent

process_message = Agent(
    name="process_message",
    model="gemini-flash-latest",
    instruction="Read the incoming support message and summarize the customer's intent in one line.",
    output_schema=str,
)

handle_bug = Agent(
    name="handle_bug",
    model="gemini-flash-latest",
    instruction="Triage the reported bug, ask for reproduction steps if missing, and draft an engineering ticket.",
    output_schema=str,
)

handle_customer_support = Agent(
    name="handle_customer_support",
    model="gemini-flash-latest",
    instruction="Answer the customer's support question directly and offer next steps.",
    output_schema=str,
)

handle_logistics = Agent(
    name="handle_logistics",
    model="gemini-flash-latest",
    instruction="Resolve the shipping or logistics request and provide tracking or delivery details.",
    output_schema=str,
)
