# Agents — generated by graphical-agents from the Graph IR (nested_schema_workflow).

from google.adk import Agent

from schemas import Order

make_order = Agent(
    name="make_order",
    model="gemini-flash-latest",
    instruction="Produce a sample Order with a customer and an optional shipping_address.",
    output_schema=Order,
)
