# Function bodies (implement the TODO stubs) — generated by graphical-agents from the Graph IR (nested_schema_workflow).

from google.adk import Event

from schemas import Order


def summarize_order(node_input: Order) -> Event:
    """Render the order as a one-line human-readable string."""
    # TODO: implement summarize_order — body not yet provided in the IR.
    output: str = ...
    return Event(output=output)
