# Workflow graph (entry module) — generated by graphical-agents from the Graph IR (nested_schema_workflow).

from google.adk import Workflow

from agents import make_order
from functions import summarize_order

root_agent = Workflow(
    name="nested_schema_workflow",
    edges=[("START", make_order, summarize_order)],
)
