# Agents — generated by graphical-agents from the Graph IR (tool_workflow).

from google.adk import Agent

from schemas import Article

summarize = Agent(
    name="summarize",
    model="gemini-flash-latest",
    instruction="Summarize the article in one sentence.",
    input_schema=Article,
    output_schema=str,
)
