# Function bodies (implement the TODO stubs) — generated by graphical-agents from the Graph IR (tool_workflow).

from google.adk import Event

from schemas import Article


def fetch_data(node_input: str) -> Event:
    """Fetch an article from a remote source."""
    # TODO: implement fetch_data — body not yet provided in the IR.
    output: Article = ...
    return Event(output=output)
