# Workflow graph (entry module) — generated by graphical-agents from the Graph IR (tool_workflow).

from google.adk import Workflow

from agents import summarize
from functions import fetch_data

root_agent = Workflow(
    name="tool_workflow",
    edges=[("START", fetch_data, summarize)],
)
