# Agent node functions — generated by graphical-agents from the Graph IR (tool_workflow).

from langchain.chat_models import init_chat_model

from state import WorkflowState


def summarize(state: WorkflowState) -> dict:
    model = init_chat_model("google_genai:gemini-flash-latest")
    prompt = f"Summarize the article in one sentence.\n\nInput:\n{state['fetch_data_output'].model_dump_json()}"
    result = model.invoke(prompt)
    return {"summarize_output": result.content}
