# Workflow graph (entry module) — generated by graphical-agents from the Graph IR (tool_workflow).

from langgraph.graph import END, START, StateGraph

from agents import summarize
from nodes import fetch_data
from state import WorkflowState

builder = StateGraph(WorkflowState)
builder.add_node("fetch_data", fetch_data)
builder.add_node("summarize", summarize)

builder.add_edge(START, "fetch_data")
builder.add_edge("fetch_data", "summarize")
builder.add_edge("summarize", END)

graph = builder.compile()
