# Run the workflow once — generated by graphical-agents from the Graph IR (tool_workflow).

from graph import graph

# TODO: replace with a real input for this workflow.
SAMPLE_INPUT = "Hello — replace with a real input for this workflow."


def main() -> None:
    result = graph.invoke({"workflow_input": SAMPLE_INPUT})
    print("Final state:", result)


if __name__ == "__main__":
    main()
