# Node functions (implement the TODO stubs) — generated by graphical-agents from the Graph IR (tool_workflow).

from schemas import Article
from state import WorkflowState


def fetch_data(state: WorkflowState) -> dict:
    """Fetch an article from a remote source."""
    node_input = state["workflow_input"]
    # TODO: implement fetch_data — body not yet provided in the IR.
    output: Article = ...
    return {"fetch_data_output": output}
