# Graph state — one key per node output (ADR-0046) — generated by graphical-agents from the Graph IR (tool_workflow).

from typing_extensions import TypedDict

from schemas import Article


class WorkflowState(TypedDict, total=False):
    workflow_input: str
    fetch_data_output: Article
    summarize_output: str
