# Run the workflow once — generated by graphical-agents from the Graph IR (feasibility_workflow).
#
# E2E stub overlay. Unlike the other live cells, this one does not just prove the
# project runs: it asserts that ADK actually traversed the router's branch
# continuation row `(generate_code, run_tests, summarize_result)` (ADR-0054).
# A live cell passes on exit code alone, so without these assertions a build
# where ADK silently ignored the continuation would still report green.

import asyncio
from uuid import uuid4

from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.genai import types

from functions import EXECUTED, TEST_REPORT
from workflow import root_agent

APP_NAME = "feasibility_workflow"
USER_ID = "user"

# TODO: replace with a real input for this workflow.
SAMPLE_INPUT = (
    "Add a --retry flag to our CLI that retries failed HTTP requests three "
    "times with exponential backoff."
)


def event_text(event) -> str:
    """Best-effort text of an event; '' when the shape is not what we expect."""
    content = getattr(event, "content", None)
    parts = getattr(content, "parts", None) or []
    return "".join(getattr(p, "text", None) or "" for p in parts)


async def main() -> None:
    session_service = InMemorySessionService()
    session_id = f"run-{uuid4().hex[:8]}"
    await session_service.create_session(
        app_name=APP_NAME, user_id=USER_ID, session_id=session_id
    )
    runner = Runner(
        agent=root_agent, app_name=APP_NAME, session_service=session_service
    )
    authors: list[str] = []
    texts: list[str] = []
    async for event in runner.run_async(
        user_id=USER_ID,
        session_id=session_id,
        new_message=types.Content(role="user", parts=[types.Part(text=SAMPLE_INPUT)]),
    ):
        print(event)
        author = getattr(event, "author", None)
        if author:
            authors.append(str(author))
        text = event_text(event)
        if text.strip():
            texts.append(text)
    final_session = await session_service.get_session(
        app_name=APP_NAME, user_id=USER_ID, session_id=session_id
    )
    print("Final session state:", final_session.state if final_session else {})

    # ---- branch-continuation assertions (ADR-0054) ----
    print("\n--- continuation check ---")
    print("stub functions executed:", EXECUTED)
    print("event authors:", authors)

    failures: list[str] = []

    # Hop 2 of the continuation row. Decisive: run_tests only runs if ADK
    # followed `(generate_code, run_tests, ...)` after the route map.
    if "run_tests" not in EXECUTED:
        failures.append(
            "run_tests never executed — ADK did not enter the branch "
            "continuation row after the route map"
        )

    # Hop 3. summarize_result is a live agent, so its presence as an event
    # author is the deterministic signal that the chain continued past run_tests.
    if authors and "summarize_result" not in authors:
        failures.append(
            "summarize_result produced no event — the continuation row stopped "
            f"at run_tests (authors seen: {authors})"
        )
    elif not authors:
        print(
            "NOTE: no event authors could be read; hop 3 unverified by author, "
            "falling back to the output-differs check below"
        )

    final_text = texts[-1] if texts else ""
    if final_text.strip() == TEST_REPORT.strip():
        failures.append(
            "the workflow's final output is run_tests' raw report — nothing "
            "consumed it, so summarize_result did not run"
        )

    if failures:
        print("\nCONTINUATION CHECK FAILED:")
        for f in failures:
            print(f"  - {f}")
        raise SystemExit(1)

    print("continuation check OK: route map -> generate_code -> run_tests -> summarize_result")


if __name__ == "__main__":
    asyncio.run(main())
